name: Simulation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: slacgismo/gridlabd:latest
    
    steps:
    - uses: actions/checkout@v2

    - name: Run simulation
      run: gridlabd input/*.glm -o output/gridlabd.json 1>output/console.txt 2>&1
      
    - name: Save results
      uses: actions/upload-artifact@v2
      with:
        name: output
        path: output/
      
